name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  Deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: "14"

    - name: Install Dependencies
      run: npm ci

    - name: Build & Deploy
      run: npm run deploy
